### ISSUE TITLE
initial HML/CSS Setup

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/awesome-world#2]
let's start at the top with HTML/CSS creation. please set up the initial files for displaying the world and styling it with CSS

**Comment by TheMapSmith** [comment]
Sure, to begin with, we'll need at least two files: an HTML file and a CSS file. Here's a basic setup:

HTML file (index.html)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive SVG World</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="svg-world">
        <!-- Icons will be inserted here -->
    </div>
    <script src="https://kit.fontawesome.com/yourkitcode.js" crossorigin="anonymous"></script>
    <script src="script.js"></script>
</body>
</html>
```
In this HTML file, we have a div with the id svg-world where we will insert our SVG icons. We are also linking to our CSS file, styles.css, and our JavaScript file, script.js.

The script tag for FontAwesome includes yourkitcode.js. You would replace "yourkitcode" with the actual kit code provided by FontAwesome when you sign up for their service.

CSS file (styles.css)
```css

body {
    background-color: #f0f0f0;
    margin: 0;
    padding: 0;
    overflow: hidden; /* to prevent scrollbars when icons move */
}

#svg-world {
    position: relative;
    width: 100vw;
    height: 100vh;
}
```

In our CSS file, we've set the body to have a light grey background color, and we've removed any default margin and padding. We've also set overflow: hidden; to prevent scrollbars from appearing when icons move outside the viewport.

We've set the #svg-world div to take up the entire viewport width and height with width: 100vw; and height: 100vh;. The position: relative; property will be useful later when we want to absolutely position our SVG icons within this div.

This is a very basic starting point. You'll probably want to adjust and add to these styles as you develop your project and get a better sense of your design.

Next, you'd start on the JavaScript to populate the #svg-world with SVG icons, but that would be the next step.

**Comment by TheMapSmith** [comment]
let's make the "landscape" a rectangle that's inset from the edge of the window 16 px. let's make the outer area a light grey, and the inside area plain white.

**Comment by TheMapSmith** [comment]
```css
body {
    background-color: #f0f0f0; /* light grey */
    margin: 0;
    padding: 16px; /* creates a 16px padding around the body */
    overflow: hidden; /* to prevent scrollbars when icons move */
}

#svg-world {
    position: relative;
    background-color: #ffffff; /* white */
    width: calc(100vw - 32px); /* subtracts the left and right padding */
    height: calc(100vh - 32px); /* subtracts the top and bottom padding */
    box-sizing: border-box; /* ensures padding doesn't increase the box's total size */
}
```
